name: Keep Render Awake

on:
  schedule:
    - cron: "*/6 * * * *"   # every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping streak service
        run: curl -s https://github-readme-streak-stats-fdlq.onrender.com/?user=Balaji-Coder06 > /dev/null
